### ISSUE TITLE
msms does not work on macOS catalina

### ISSUE THREAD

**Issue by YoshitakaMo** [schlessingerlab/pyvol#1]
Hi,

I use this excellent pyvol plugin on macOS Mojave. However, after I upgraded to macOS catalina, the pyvol plugin does not work probably because catalina does no longer support 32 bit binary `msms` which may be required for the pyvol process. Unfortunately, I could not find the source code of `msms` and it seems no longer maintained. Is there any way to work the pyvol plugin on macOS catalina?
<img width="856" alt="スクリーンショット 2019-11-03 1 43 00" src="https://user-images.githubusercontent.com/16487484/68074145-4cd1e500-fddb-11e9-82bd-5df921f3b340.png">

**Comment by rhs2132** [comment]
Thanks for bringing this up. The program (msms) used for surface triangulation is only available pre-compiled right now. The version for MacOS is only available in a 32 bit binary right now. I have reached out to Scripps to see if they will release a 64 bit version or let me compile the source code. If they won't do that, I can integrate a different surface triangulation program. I'll update you when I have a fix.

**Comment by rhs2132** [comment]
I haven't gotten any response from Scripps yet. I am not sure when I will have time to get to implementing a work around on Catalina. I'll reach out when I get to it.
