### ISSUE TITLE
Using pyvol's API

### ISSUE THREAD

**Issue by orthonalmatrix** [schlessingerlab/pyvol#3]
I would like to use pyvol directly from python in order to script the processing of large amounts of data. I am getting a file not found error when I try to compute the pockets:

import pyvol
pyvol.identify.pocket('tunnelcontact21ticN9_hog/state_apo_All_21tic_N9_0_0.pdb')

Process Failed: msms -if /tmp/tmpfyotfmi3/pyvol.xyzr -of /tmp/tmpfyotfmi3/pyvol_msms -probe_radius 3.4 -no_area -noh
MSMS failed to run correctly for /tmp/tmpfyotfmi3/pyvol_msms
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
~/bin/anaconda3/envs/ms/lib/python3.6/site-packages/pyvol/spheres.py in read_msms_output(msms_template)
    187             try:
--> 188                 verts_raw = pd.read_csv("{0}.vert".format(msms_template), sep='\s+', skiprows=3, dtype=np.float_, header=None, encoding='latin1').values
    189                 faces = pd.read_csv("{0}.face".format(msms_template), sep='\s+', skiprows=3, usecols=[0, 1, 2], dtype=np.int_, header=None, encoding='latin1').values

~/bin/anaconda3/envs/ms/lib/python3.6/site-packages/pandas/io/parsers.py in parser_f(filepath_or_buffer, sep, delimiter, header, names, index_col, usecols, squeeze, prefix, mangle_dupe_cols, dtype, engine, converters, true_values, false_values, skipinitialspace, skiprows, nrows, na_values, keep_default_na, na_filter, verbose, skip_blank_lines, parse_dates, infer_datetime_format, keep_date_col, date_parser, dayfirst, iterator, chunksize, compression, thousands, decimal, lineterminator, quotechar, quoting, escapechar, comment, encoding, dialect, tupleize_cols, error_bad_lines, warn_bad_lines, skipfooter, doublequote, delim_whitespace, low_memory, memory_map, float_precision)
    677             warn_bad_lines=warn_bad_lines,
--> 678             error_bad_lines=error_bad_lines,
    679             low_memory=low_memory,

~/bin/anaconda3/envs/ms/lib/python3.6/site-packages/pandas/io/parsers.py in _read(filepath_or_buffer, kwds)
    439     fp_or_buf, _, compression, should_close = get_filepath_or_buffer(
--> 440         filepath_or_buffer, encoding, compression
    441     )

~/bin/anaconda3/envs/ms/lib/python3.6/site-packages/pandas/io/parsers.py in __init__(self, f, engine, **kwds)
    786             col += w
--> 787 
    788     kwds["colspecs"] = colspecs

~/bin/anaconda3/envs/ms/lib/python3.6/site-packages/pandas/io/parsers.py in _make_engine(self, engine)
   1013                 len(quotechar) == 1
-> 1014                 and ord(quotechar) > 127
   1015                 and engine not in ("python", "python-fwf")

~/bin/anaconda3/envs/ms/lib/python3.6/site-packages/pandas/io/parsers.py in __init__(self, src, **kwds)
   1707                     warnings.warn(
-> 1708                         (
   1709                             "Both a converter and dtype were specified "

pandas/_libs/parsers.pyx in pandas._libs.parsers.TextReader.__cinit__()

pandas/_libs/parsers.pyx in pandas._libs.parsers.TextReader._setup_parser_source()

FileNotFoundError: File b'/tmp/tmpfyotfmi3/pyvol_msms.vert' does not exist

During handling of the above exception, another exception occurred:

OSError                                   Traceback (most recent call last)
<ipython-input-62-3edeea590312> in <module>
----> 1 pyvol.identify.pocket('tunnelcontact21ticN9_hog/state_apo_All_21tic_N9_0_0.pdb')

~/bin/anaconda3/envs/ms/lib/python3.6/site-packages/pyvol/identify.py in pocket(prot_file, mode, lig_file, coordinate, resid, residue_coordinates, min_rad, max_rad, lig_excl_rad, lig_incl_rad, subdivide, minimum_volume, min_subpocket_rad, min_subpocket_surf_rad, max_clusters, prefix, output_dir, constrain_inputs)
     97     pl_s = p_s + l_s
     98 
---> 99     pl_bs = pl_s.calculate_surface(probe_radius=max_rad)[0]
    100     logger.debug("Outer boundary surface calculated")
    101 

~/bin/anaconda3/envs/ms/lib/python3.6/site-packages/pyvol/spheres.py in calculate_surface(self, probe_radius, cavity_atom, coordinate, all_components, exclusionary_radius, largest_only, noh, minimum_volume)
    197 
    198         if not all_components:
--> 199             verts_raw, vertices, faces = read_msms_output(msms_template)
    200 
    201             mesh = trimesh.base.Trimesh(vertices=vertices, faces=faces)

~/bin/anaconda3/envs/ms/lib/python3.6/site-packages/pyvol/spheres.py in read_msms_output(msms_template)
    190             except IOError:
    191                 logger.error("MSMS failed to run correctly for {0}".format(msms_template))
--> 192                 raise IOError
    193             else:
    194                 vertices = np.zeros((verts_raw.shape[0] + 1, 3))

OSError: 

Thanks so much for you help!

**Comment by rhs2132** [comment]
The problem here is that the surface triangulation is failing. I forgot to gracefully catch that error when updating the logger. Would you mind sharing the input pdb file with me so I can see what is going on? If you are comfortable sharing the file, my email is ryan.smith@icahn.mssm.edu.

Otherwise, have you run surface calculation from within PyMOL?

**Comment by orthonalmatrix** [comment]
I have still been unable to install pyvol in pymol 1.8.x and 1.7.x. I used the new gui installer zip file, but it says it installed but failed to initialize.

PYMOL give this on startup

pyvol.plugin:             INFO    PyVOL not imported; installing from local cache or PyPI to use
Unable to initialize plugin 'pyvol_gui' (pmg_tk.startup.pyvol_gui).

**Comment by rhs2132** [comment]
I pushed some changes that should make PyVOL compatible with PyMOL 1.7.4+. I won't have time to test them under these earlier PyMOL versions until later this weekend, but version 1.2.45+ (gui version 1.1.12+) should support earlier PyMOLs.

**Comment by orthonalmatrix** [comment]
I see bio-pyvol==1.2.44 is available but not 1.2.45

**Comment by orthonalmatrix** [comment]
I've used conda to create a new environment of python3.6.9. I installed bio-pyvol via pip. Now I get

import pyvol
print(pyvol.__version__)
1.2.44
pyvol.identify.pocket('/home/eddie/shareddata/namdoutput/analysis_apo/tunnelcontact21ticN9_hog/state_apo_All_21tic_N9_0_0.pdb')

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-3-45235fa30458> in <module>
----> 1 pyvol.identify.pocket('/home/eddie/shareddata/namdoutput/analysis_apo/tunnelcontact21ticN9_hog/state_apo_All_21tic_N9_0_0.pdb')

AttributeError: module 'pyvol' has no attribute 'identify'

**Comment by rhs2132** [comment]
If you are still interested in using this code, I've pushed some major updates in the last couple weeks. Try installing 1.6.8 and see if that works. The new syntax would be:

from pyvol import identify
identify.pocket_wrapper(prot_file="....pdb")
