### ISSUE TITLE
Setup in pymol 2.3.3

### ISSUE THREAD

**Issue by eackad** [schlessingerlab/pyvol#4]
I've installed a windows 30 day trial version of pymol. I downloaded and installed the GUI. This installed well. However, when I click on Plugin -> pyVOL it gives the following error:

 PyMOL(TM) 2.3.3 - Incentive Product
 Copyright (C) Schrodinger, LLC
 
 This Executable Build integrates and extends Open-Source PyMOL.
 Detected OpenGL version 4.6. Shaders available.
 Detected GLSL version 4.60.
 OpenGL graphics engine:
  GL_VENDOR:   NVIDIA Corporation
  GL_RENDERER: GeForce GTX 1080 Ti/PCIe/SSE2
  GL_VERSION:  4.6.0 NVIDIA 425.31
No License File - For Evaluation Only (30 days remaining)
 Detected 8 CPU cores.  Enabled multithreaded rendering.
 ObjectMolecule: Read crystal symmetry information.
 CmdLoad: PDB-string loaded into object "state_apo_All_21tic_N9_0_0", state 1.
pyvol.plugin:              INFO     PyVOL not imported; installing from local cache or PyPI to use
Traceback (most recent call last):
  File "D:\Program_files_windows\lib\site-packages\pmg_tk\startup\pyvol_gui\__init__.py", line 52, in pyvol_window
    refresh_installation_status(form)
  File "D:\Program_files_windows\lib\site-packages\pmg_tk\startup\pyvol_gui\__init__.py", line 259, in refresh_installation_status
    new_msms_exe = form.msms_new_label.getText()
AttributeError: 'QLabel' object has no attribute 'getText'

**Comment by rhs2132** [comment]
Thanks for posting that error. I'm confused why my own test didn't catch it. QLabel uses the text() function rather than getText(). I've fixed that and pushed it out into the new gui/backend 1.1.7/1.2.39 respectively. Let me know if you have any more problems.
