### ISSUE TITLE
PyVol multiple pockets volumes calculation

### ISSUE THREAD

**Issue by islem1994** [schlessingerlab/pyvol#7]
Hello !

I am a PhD student in Life and Health sciences at Caen University.
In my thesis project, I'm currently analysing a database where noble gases binding sites were modelled in all PDB entries. I'm looking for interesting potential proteins that bind noble gases and trying to characterize and distinguish those binding sites based on several criteria such as their volumes values.

I choose PyVol for this purpose because I'm allowed to calculate specific binding sites by providing specific coordinates (using the specific mode).

It's easy to use this plugin manually on one protein structure. However, I want to run it automatically on a list of protein structures with specific noble gas binding sites coordinates.
Is there any idea to manage this issue?

Thanks in advance.
Best regards.

---
Islem HAMMAMI – PhD Student

GIP CYCERON - Unité ISTCT - Equipe CERVOxy
Bd H Becquerel 14074 Caen
www.istct.cyceron.fr

AIR LIQUIDE SANTE INTERNATIONAL
Paris Innovation Campus
1, chemin de la Porte des Loges
78350 Les loges en Josas - FRANCE
www.airliquide.com

**Comment by rhs2132** [comment]
Sorry about the delay getting back to you. That functionality should be very manageable with the current implementation. I think that using the 'coordinates' keyword specification running in the 'specific' mode should do what you want. The documentation is located: https://schlessinger-lab.github.io/pyvol/pocket_specification.html

I have run into one instance in which coordinate specification has given weird results and haven't tracked down that bug yet, so let me know if you run into any issues and I'll take a look. 

As for running everything sequentially, I would programmatically invoke 'pyvol.identify.pocket_wrapper' using the arguments  enumerated in 'pyvol.pymol_interface.cmdline'. These are documented: https://schlessinger-lab.github.io/pyvol/pyvol.html

If you need any help writing such a script, let me know.

**Comment by islem1994** [comment]
Thank you for your response.

I have already written my script. However, whenever I check and load the pockets volumes, I notice that there are some artefacts such as:

- Pyvol detects pockets with my specific coordinates (of the gas atome)  but the gas atome of interest is too fra from that pocket.

For some proteins lists, calculations stoped suddenly and I didn't understand the error message.
In fact, when I loop over a list of protein, I forced the elimination brackets from coordinates while creating configuration files (see attached example of cfg_file), so they can be loaded later. 

Here is what I do:

  `/usr/local/SOFTS/PYMOL/2.4.0_178/bin/python  ligase_E2/generate_cfg.py 

here is the error message :

`pyvol.utilities:        ERROR           Process Failed: msms -if /tmp/tmpwk_6yp7f/pyvol.xyzr -of /tmp/tmpwk_6yp7f/pyvol_msms -probe_radius 1.4 -no_area -noh -one_cavity 1 9708
Traceback (most recent call last):
  File "ligase_E2/generate_cfg.py", line 38, in <module>
    identify.pocket_wrapper(**options)
  File "/usr/local/SOFTS/PYMOL/2.4.0_178/lib/python3.7/site-packages/pyvol/identify.py", line 186, in pocket_wrapper
    all_pockets, output_opts = pocket(**opts)
  File "/usr/local/SOFTS/PYMOL/2.4.0_178/lib/python3.7/site-packages/pyvol/identify.py", line 143, in pocket
    bp_bs = pa_s.calculate_surface(probe_radius=opts.get("min_rad"), coordinate=id_coord)[0]
  File "/usr/local/SOFTS/PYMOL/2.4.0_178/lib/python3.7/site-packages/pyvol/spheres.py", line 181, in calculate_surface
    utilities.run_cmd(msms_cmd)
  File "/usr/local/SOFTS/PYMOL/2.4.0_178/lib/python3.7/site-packages/pyvol/utilities.py", line 215, in run_cmd
    subprocess.check_output(opt_strs, stderr=subprocess.STDOUT)
  File "/usr/local/SOFTS/PYMOL/2.4.0_178/lib/python3.7/subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "/usr/local/SOFTS/PYMOL/2.4.0_178/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['msms', '-if', '/tmp/tmpwk_6yp7f/pyvol.xyzr', '-of', '/tmp/tmpwk_6yp7f/pyvol_msms', '-probe_radius', '1.4', '-no_area', '-noh', '-one_cavity', '1', '9708']' returned non-zero exit status 1.
`
I will be grateful  if you can help me with this error.
Thank you.

**Comment by islem1994** [comment]
Thank you for your response.

I have already written my script. However, whenever I check and load the pockets volumes, I notice that there are some artefacts such as:

- Pyvol detects pockets with my specific coordinates (of the gas atome)  but the gas atome of interest is too fra from that pocket.

For some proteins lists, calculations stoped suddenly and I didn't understand the error message.
In fact, when I loop over a list of protein, I forced the elimination brackets from coordinates while creating configuration files (see attached example of cfg_file), so they can be loaded later. 

Here is what I do:

  `/usr/local/SOFTS/PYMOL/2.4.0_178/bin/python  ligase_E2/generate_cfg.py 

here is the error message :

`pyvol.utilities:        ERROR           Process Failed: msms -if /tmp/tmpwk_6yp7f/pyvol.xyzr -of /tmp/tmpwk_6yp7f/pyvol_msms -probe_radius 1.4 -no_area -noh -one_cavity 1 9708
Traceback (most recent call last):
  File "ligase_E2/generate_cfg.py", line 38, in <module>
    identify.pocket_wrapper(**options)
  File "/usr/local/SOFTS/PYMOL/2.4.0_178/lib/python3.7/site-packages/pyvol/identify.py", line 186, in pocket_wrapper
    all_pockets, output_opts = pocket(**opts)
  File "/usr/local/SOFTS/PYMOL/2.4.0_178/lib/python3.7/site-packages/pyvol/identify.py", line 143, in pocket
    bp_bs = pa_s.calculate_surface(probe_radius=opts.get("min_rad"), coordinate=id_coord)[0]
  File "/usr/local/SOFTS/PYMOL/2.4.0_178/lib/python3.7/site-packages/pyvol/spheres.py", line 181, in calculate_surface
    utilities.run_cmd(msms_cmd)
  File "/usr/local/SOFTS/PYMOL/2.4.0_178/lib/python3.7/site-packages/pyvol/utilities.py", line 215, in run_cmd
    subprocess.check_output(opt_strs, stderr=subprocess.STDOUT)
  File "/usr/local/SOFTS/PYMOL/2.4.0_178/lib/python3.7/subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "/usr/local/SOFTS/PYMOL/2.4.0_178/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['msms', '-if', '/tmp/tmpwk_6yp7f/pyvol.xyzr', '-of', '/tmp/tmpwk_6yp7f/pyvol_msms', '-probe_radius', '1.4', '-no_area', '-noh', '-one_cavity', '1', '9708']' returned non-zero exit status 1.
`
I will be grateful  if you can help me with this error.
Thank you.

**Comment by islem1994** [comment]
Thank you for your response.

I have already written my script. However, whenever I check and load the pockets volumes, I notice that there are some artefacts such as:

- Pyvol detects pockets with my specific coordinates (of the gas atome)  but the gas atome of interest is too fra from that pocket.

For some proteins lists, calculations stoped suddenly and I didn't understand the error message.
In fact, when I loop over a list of protein, I forced the elimination brackets from coordinates while creating configuration files (see attached example of cfg_file), so they can be loaded later. 

Here is what I do:

  `/usr/local/SOFTS/PYMOL/2.4.0_178/bin/python`  ligase_E2/generate_cfg.py 

here is the error message :

`pyvol.utilities:        ERROR           Process Failed: msms -if /tmp/tmpwk_6yp7f/pyvol.xyzr -of /tmp/tmpwk_6yp7f/pyvol_msms -probe_radius 1.4 -no_area -noh -one_cavity 1 9708
Traceback (most recent call last):
  File "ligase_E2/generate_cfg.py", line 38, in <module>
    identify.pocket_wrapper(**options)
  File "/usr/local/SOFTS/PYMOL/2.4.0_178/lib/python3.7/site-packages/pyvol/identify.py", line 186, in pocket_wrapper
    all_pockets, output_opts = pocket(**opts)
  File "/usr/local/SOFTS/PYMOL/2.4.0_178/lib/python3.7/site-packages/pyvol/identify.py", line 143, in pocket
    bp_bs = pa_s.calculate_surface(probe_radius=opts.get("min_rad"), coordinate=id_coord)[0]
  File "/usr/local/SOFTS/PYMOL/2.4.0_178/lib/python3.7/site-packages/pyvol/spheres.py", line 181, in calculate_surface
    utilities.run_cmd(msms_cmd)
  File "/usr/local/SOFTS/PYMOL/2.4.0_178/lib/python3.7/site-packages/pyvol/utilities.py", line 215, in run_cmd
    subprocess.check_output(opt_strs, stderr=subprocess.STDOUT)
  File "/usr/local/SOFTS/PYMOL/2.4.0_178/lib/python3.7/subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "/usr/local/SOFTS/PYMOL/2.4.0_178/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['msms', '-if', '/tmp/tmpwk_6yp7f/pyvol.xyzr', '-of', '/tmp/tmpwk_6yp7f/pyvol_msms', '-probe_radius', '1.4', '-no_area', '-noh', '-one_cavity', '1', '9708']' returned non-zero exit status 1.
`
I will be grateful  if you can help me with this error.
Thank you.

**Comment by islem1994** [comment]
[example_of_cfg_file.txt](https://github.com/schlessinger-lab/pyvol/files/5143210/example_of_cfg_file.txt)

Thank you for your response.

I have already written my script. However, whenever I check and load the pockets volumes, I notice that there are some artefacts such as:

   
 Pyvol detects pockets with my specific coordinates (of the gas atome) but the gas atome of interest is too fra from that pocket.

For some proteins lists, calculations stoped suddenly and I didn't understand the error message.
In fact, when I loop over a list of protein, I forced the elimination brackets from coordinates while creating configuration files (see attached example of cfg_file), so they can be loaded later.

Here is what I do:

`/usr/local/SOFTS/PYMOL/2.4.0_178/bin/python ligase_E2/generate_cfg.py`

here is the error message :

> pyvol.utilities: ERROR Process Failed: msms -if /tmp/tmpwk_6yp7f/pyvol.xyzr -of /tmp/tmpwk_6yp7f/pyvol_msms -probe_radius 1.4 -no_area -noh -one_cavity 1 9708 Traceback (most recent call last): File "ligase_E2/generate_cfg.py", line 38, in <module> identify.pocket_wrapper(**options) File "/usr/local/SOFTS/PYMOL/2.4.0_178/lib/python3.7/site-packages/pyvol/identify.py", line 186, in pocket_wrapper all_pockets, output_opts = pocket(**opts) File "/usr/local/SOFTS/PYMOL/2.4.0_178/lib/python3.7/site-packages/pyvol/identify.py", line 143, in pocket bp_bs = pa_s.calculate_surface(probe_radius=opts.get("min_rad"), coordinate=id_coord)[0] File "/usr/local/SOFTS/PYMOL/2.4.0_178/lib/python3.7/site-packages/pyvol/spheres.py", line 181, in calculate_surface utilities.run_cmd(msms_cmd) File "/usr/local/SOFTS/PYMOL/2.4.0_178/lib/python3.7/site-packages/pyvol/utilities.py", line 215, in run_cmd subprocess.check_output(opt_strs, stderr=subprocess.STDOUT) File "/usr/local/SOFTS/PYMOL/2.4.0_178/lib/python3.7/subprocess.py", line 411, in check_output **kwargs).stdout File "/usr/local/SOFTS/PYMOL/2.4.0_178/lib/python3.7/subprocess.py", line 512, in run output=stdout, stderr=stderr) subprocess.CalledProcessError: Command '['msms', '-if', '/tmp/tmpwk_6yp7f/pyvol.xyzr', '-of', '/tmp/tmpwk_6yp7f/pyvol_msms', '-probe_radius', '1.4', '-no_area', '-noh', '-one_cavity', '1', '9708']' returned non-zero exit status 1.

I will be grateful if you can help me with this error.
Thank you.
