### ISSUE TITLE
Installation guide is down

### ISSUE THREAD

**Issue by felipepenha** [schlessingerlab/pyvol#8]
I cannot access the installation guide link: https://schlessingerlab.github.io/pyvol/install.html

**Comment by rhs2132** [comment]
The installation documentation was moved to: https://schlessinger-lab.github.io/pyvol/install.html
which is just different by a single "-". However, I just followed the link and both the readme and documentation website are not showing the most recent uploads. That page as it currently stands is deprecated. 

Actually the installers themselves aren't correctly updated. Somehow, the online representation of the project has fallen behind by several important updates that I believe are included in the package management repositories (i.e. pip and conda). I'll try to update everything by tonight.
